# Generated by Django 4.2.27 on 2025-12-07 12:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobaleStatistik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letzter_lerntag', models.DateField(blank=True, null=True)),
                ('streak', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Globale Statistik',
                'verbose_name_plural': 'Globale Statistik',
            },
        ),
        migrations.CreateModel(
            name='Karteikarte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begriff', models.CharField(max_length=200)),
                ('definition', models.TextField()),
                ('beispiele', models.TextField(blank=True, help_text='Anwendungsbeispiele')),
                ('zusatz_label', models.CharField(blank=True, help_text="Name des Zusatzfeldes (z.B. 'Herkunft', 'Synonym')", max_length=50)),
                ('zusatz_wert', models.TextField(blank=True, help_text='Inhalt des Zusatzfeldes')),
                ('fach', models.IntegerField(choices=[(1, 'Fach 1'), (2, 'Fach 2'), (3, 'Fach 3'), (4, 'Fach 4'), (5, 'Fach 5')], default=1)),
                ('naechste_wiederholung', models.DateField(default=datetime.date.today)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Karteikarte',
                'verbose_name_plural': 'Karteikarten',
                'ordering': ['begriff'],
            },
        ),
        migrations.CreateModel(
            name='Lernblock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('beschreibung', models.TextField(blank=True)),
                ('bidirektional', models.BooleanField(default=False, help_text='Auch rückwärts lernen (Definition → Begriff)')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lernblock',
                'verbose_name_plural': 'Lernblöcke',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lernergebnis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modus', models.CharField(choices=[('klassisch', 'Klassisch'), ('rueckwaerts', 'Rückwärts'), ('multiple_choice', 'Multiple Choice')], default='klassisch', max_length=20)),
                ('richtig', models.BooleanField()),
                ('zeitstempel', models.DateTimeField(auto_now_add=True)),
                ('karte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ergebnisse', to='karteikarten.karteikarte')),
            ],
            options={
                'verbose_name': 'Lernergebnis',
                'verbose_name_plural': 'Lernergebnisse',
                'ordering': ['-zeitstempel'],
            },
        ),
        migrations.AddField(
            model_name='karteikarte',
            name='lernblock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='karten', to='karteikarten.lernblock'),
        ),
        migrations.CreateModel(
            name='TagesStatistik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(default=datetime.date.today)),
                ('gelernt', models.IntegerField(default=0)),
                ('richtig', models.IntegerField(default=0)),
                ('falsch', models.IntegerField(default=0)),
                ('lernblock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagesstatistiken', to='karteikarten.lernblock')),
            ],
            options={
                'verbose_name': 'Tagesstatistik',
                'verbose_name_plural': 'Tagesstatistiken',
                'ordering': ['-datum'],
                'unique_together': {('lernblock', 'datum')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='karteikarte',
            unique_together={('lernblock', 'begriff')},
        ),
    ]
