# Generated by Django 4.2.27 on 2025-12-07 13:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('karteikarten', '0002_jahrgangsstufe_schulfach_lernblock_thema_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tagesstatistik',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='lernergebnis',
            name='benutzer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lernergebnisse', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tagesstatistik',
            name='benutzer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tagesstatistiken', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='tagesstatistik',
            unique_together={('benutzer', 'lernblock', 'datum')},
        ),
        migrations.CreateModel(
            name='BenutzerStatistik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letzter_lerntag', models.DateField(blank=True, null=True)),
                ('streak', models.IntegerField(default=0)),
                ('gesamt_gelernt', models.IntegerField(default=0)),
                ('gesamt_richtig', models.IntegerField(default=0)),
                ('benutzer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistik', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Benutzerstatistik',
                'verbose_name_plural': 'Benutzerstatistiken',
            },
        ),
        migrations.CreateModel(
            name='BenutzerLernblock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hinzugefuegt_am', models.DateTimeField(auto_now_add=True)),
                ('benutzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lernbloecke', to=settings.AUTH_USER_MODEL)),
                ('lernblock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benutzer_zuordnungen', to='karteikarten.lernblock')),
            ],
            options={
                'verbose_name': 'Benutzer-Lernblock',
                'verbose_name_plural': 'Benutzer-Lernblöcke',
                'unique_together': {('benutzer', 'lernblock')},
            },
        ),
        migrations.CreateModel(
            name='BenutzerKarteStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fach', models.IntegerField(choices=[(1, 'Fach 1'), (2, 'Fach 2'), (3, 'Fach 3'), (4, 'Fach 4'), (5, 'Fach 5')], default=1)),
                ('naechste_wiederholung', models.DateField(default=datetime.date.today)),
                ('benutzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='karten_status', to=settings.AUTH_USER_MODEL)),
                ('karte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benutzer_status', to='karteikarten.karteikarte')),
            ],
            options={
                'verbose_name': 'Benutzer-Kartenstatus',
                'verbose_name_plural': 'Benutzer-Kartenstatus',
                'unique_together': {('benutzer', 'karte')},
            },
        ),
    ]
