# Generated by Django 4.2.27 on 2025-12-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karteikarten', '0004_benutzerstatistik_bevorzugte_jahrgangsstufe'),
    ]

    operations = [
        migrations.AddField(
            model_name='benutzerstatistik',
            name='muss_passwort_aendern',
            field=models.BooleanField(default=False, help_text='Benutzer muss beim naechsten Login sein Passwort aendern'),
        ),
    ]
