# Generated by Django 4.2.27 on 2025-12-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karteikarten', '0005_add_muss_passwort_aendern'),
    ]

    operations = [
        migrations.AddField(
            model_name='lernblock',
            name='lehrbuch',
            field=models.CharField(blank=True, help_text='Optionale Angabe des verwendeten Lehrbuchs', max_length=200),
        ),
    ]
