# Generated by Django 6.1 on 2026-08-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("karteikarten", "0007_add_lehrwerk_hierarchy_and_import"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lernergebnis",
            name="modus",
            field=models.CharField(
                choices=[
                    ("klassisch", "Klassisch"),
                    ("rueckwaerts", "Rückwärts"),
                    ("multiple_choice", "Multiple Choice"),
                    ("tippen", "Eintippen"),
                ],
                default="klassisch",
                max_length=20,
            ),
        ),
    ]
