# Generated by Django 6.1 on 2026-08-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("karteikarten", "0008_alter_lernergebnis_modus"),
    ]

    operations = [
        migrations.AddField(
            model_name="benutzerstatistik",
            name="bevorzugter_modus",
            field=models.CharField(
                choices=[
                    ("klassisch", "Klassisch"),
                    ("rueckwaerts", "Rückwärts"),
                    ("multiple_choice", "Multiple Choice"),
                    ("tippen", "Eintippen"),
                ],
                default="klassisch",
                help_text="Womit die Abfrage startet, ohne dass jedes Mal gefragt wird",
                max_length=20,
            ),
        ),
    ]
